package com.example.source11_api30.lyc;

class LyricData {

    public static final String lyc = "[\n" +
            "    {\n" +
            "        \"desc\":\"原曲《春风有信》\",\n" +
            "        \"lastTime\":0,\n" +
            "        \"nextTime\":1870,\n" +
            "        \"startTime\":1420\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"作词 : 岁予\",\n" +
            "        \"lastTime\":1420,\n" +
            "        \"nextTime\":2320,\n" +
            "        \"startTime\":1870\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"作曲 : 果子狸\",\n" +
            "        \"lastTime\":1870,\n" +
            "        \"nextTime\":2760,\n" +
            "        \"startTime\":2320\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"策划：轻不言\",\n" +
            "        \"lastTime\":2320,\n" +
            "        \"nextTime\":3240,\n" +
            "        \"startTime\":2760\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"编曲：郑哆哆（蘸泡面的酱）\",\n" +
            "        \"lastTime\":2760,\n" +
            "        \"nextTime\":3710,\n" +
            "        \"startTime\":3240\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"演唱：尸体\",\n" +
            "        \"lastTime\":3240,\n" +
            "        \"nextTime\":4190,\n" +
            "        \"startTime\":3710\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"混音：梨酣\",\n" +
            "        \"lastTime\":3710,\n" +
            "        \"nextTime\":4660,\n" +
            "        \"startTime\":4190\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"画手：从心\",\n" +
            "        \"lastTime\":4190,\n" +
            "        \"nextTime\":5180,\n" +
            "        \"startTime\":4660\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"题字：橦儿\",\n" +
            "        \"lastTime\":4660,\n" +
            "        \"nextTime\":5610,\n" +
            "        \"startTime\":5180\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"------------------------------------------------\",\n" +
            "        \"lastTime\":5180,\n" +
            "        \"nextTime\":6150,\n" +
            "        \"startTime\":5610\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"谢阿娇原著 极其敷衍工作室出品 全一期现代言情广播剧《斯文败类》ED《悸动》\",\n" +
            "        \"lastTime\":5610,\n" +
            "        \"nextTime\":6720,\n" +
            "        \"startTime\":6150\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"策划：干挑面【极其敷衍】\",\n" +
            "        \"lastTime\":6150,\n" +
            "        \"nextTime\":7290,\n" +
            "        \"startTime\":6720\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"填词：洛君浅【DL_工作室】\",\n" +
            "        \"lastTime\":6720,\n" +
            "        \"nextTime\":7820,\n" +
            "        \"startTime\":7290\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"歌手：纸巾Felicity【KA.U】\",\n" +
            "        \"lastTime\":7290,\n" +
            "        \"nextTime\":8380,\n" +
            "        \"startTime\":7820\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"后期：樱庭落\",\n" +
            "        \"lastTime\":7820,\n" +
            "        \"nextTime\":8830,\n" +
            "        \"startTime\":8380\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"画师：狐骊【极其敷衍】\",\n" +
            "        \"lastTime\":8380,\n" +
            "        \"nextTime\":9340,\n" +
            "        \"startTime\":8830\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"海报：愁时【极其敷衍】\",\n" +
            "        \"lastTime\":8830,\n" +
            "        \"nextTime\":9970,\n" +
            "        \"startTime\":9340\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"如果有命中注定，\",\n" +
            "        \"lastTime\":9340,\n" +
            "        \"nextTime\":18910,\n" +
            "        \"startTime\":9970\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"别问是否冲动，\",\n" +
            "        \"lastTime\":9970,\n" +
            "        \"nextTime\":22280,\n" +
            "        \"startTime\":18910\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"还是未曾忘那时一瞥惊鸿，\",\n" +
            "        \"lastTime\":18910,\n" +
            "        \"nextTime\":27570,\n" +
            "        \"startTime\":22280\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是已模糊的身影，\",\n" +
            "        \"lastTime\":22280,\n" +
            "        \"nextTime\":30910,\n" +
            "        \"startTime\":27570\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"再次相遇悸动，\",\n" +
            "        \"lastTime\":27570,\n" +
            "        \"nextTime\":33860,\n" +
            "        \"startTime\":30910\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"偏要将隐晦爱意说的坦诚，\",\n" +
            "        \"lastTime\":30910,\n" +
            "        \"nextTime\":40290,\n" +
            "        \"startTime\":33860\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"像夏夜漫天流萤，\",\n" +
            "        \"lastTime\":33860,\n" +
            "        \"nextTime\":46090,\n" +
            "        \"startTime\":40290\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"微光汇成星空，\",\n" +
            "        \"lastTime\":40290,\n" +
            "        \"nextTime\":49260,\n" +
            "        \"startTime\":46090\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"经年的懵懂终于开始萌动，\",\n" +
            "        \"lastTime\":46090,\n" +
            "        \"nextTime\":55010,\n" +
            "        \"startTime\":49260\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"也渐渐忘记初衷，\",\n" +
            "        \"lastTime\":49260,\n" +
            "        \"nextTime\":58310,\n" +
            "        \"startTime\":55010\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"不再陷于旧梦，\",\n" +
            "        \"lastTime\":55010,\n" +
            "        \"nextTime\":61370,\n" +
            "        \"startTime\":58310\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"向春风借一点勇气来相拥，\",\n" +
            "        \"lastTime\":58310,\n" +
            "        \"nextTime\":67660,\n" +
            "        \"startTime\":61370\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"颠倒错乱的流程却也逐渐让暧昧滋生，\",\n" +
            "        \"lastTime\":61370,\n" +
            "        \"nextTime\":74050,\n" +
            "        \"startTime\":67660\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"向月亮借一点温柔在吻中，\",\n" +
            "        \"lastTime\":67660,\n" +
            "        \"nextTime\":82160,\n" +
            "        \"startTime\":74050\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是你成真的美梦，\",\n" +
            "        \"lastTime\":74050,\n" +
            "        \"nextTime\":85450,\n" +
            "        \"startTime\":82160\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"或我青春的始终，\",\n" +
            "        \"lastTime\":82160,\n" +
            "        \"nextTime\":88970,\n" +
            "        \"startTime\":85450\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是我们在对的时间又相逢，\",\n" +
            "        \"lastTime\":85450,\n" +
            "        \"nextTime\":95240,\n" +
            "        \"startTime\":88970\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"故事或许才开始但是结局早已注定，\",\n" +
            "        \"lastTime\":88970,\n" +
            "        \"nextTime\":101760,\n" +
            "        \"startTime\":95240\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是谁先心动也无需分太清，\",\n" +
            "        \"lastTime\":95240,\n" +
            "        \"nextTime\":109690,\n" +
            "        \"startTime\":101760\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"从此每一场电影，\",\n" +
            "        \"lastTime\":101760,\n" +
            "        \"nextTime\":113170,\n" +
            "        \"startTime\":109690\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"每一个特别的心动，\",\n" +
            "        \"lastTime\":109690,\n" +
            "        \"nextTime\":116740,\n" +
            "        \"startTime\":113170\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"都有你见证，\",\n" +
            "        \"lastTime\":113170,\n" +
            "        \"nextTime\":118640,\n" +
            "        \"startTime\":116740\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"而我虔诚的歌颂，\",\n" +
            "        \"lastTime\":116740,\n" +
            "        \"nextTime\":121660,\n" +
            "        \"startTime\":118640\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"致往后余生，\",\n" +
            "        \"lastTime\":118640,\n" +
            "        \"nextTime\":125940,\n" +
            "        \"startTime\":121660\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"如果有命中注定，\",\n" +
            "        \"lastTime\":121660,\n" +
            "        \"nextTime\":126160,\n" +
            "        \"startTime\":125940\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"像夏夜漫天流萤，\",\n" +
            "        \"lastTime\":125940,\n" +
            "        \"nextTime\":131710,\n" +
            "        \"startTime\":126160\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"微光汇成星空，\",\n" +
            "        \"lastTime\":126160,\n" +
            "        \"nextTime\":135050,\n" +
            "        \"startTime\":131710\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"经年的懵懂终于开始萌动，\",\n" +
            "        \"lastTime\":131710,\n" +
            "        \"nextTime\":140630,\n" +
            "        \"startTime\":135050\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"也渐渐忘记初衷，\",\n" +
            "        \"lastTime\":135050,\n" +
            "        \"nextTime\":143910,\n" +
            "        \"startTime\":140630\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"不再陷于旧梦，\",\n" +
            "        \"lastTime\":140630,\n" +
            "        \"nextTime\":147400,\n" +
            "        \"startTime\":143910\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"向春风借一点勇气来相拥，\",\n" +
            "        \"lastTime\":143910,\n" +
            "        \"nextTime\":153500,\n" +
            "        \"startTime\":147400\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"颠倒错乱的流程却也逐渐让暧昧滋生，\",\n" +
            "        \"lastTime\":147400,\n" +
            "        \"nextTime\":160540,\n" +
            "        \"startTime\":153500\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"向月亮借一点温柔在吻中，\",\n" +
            "        \"lastTime\":153500,\n" +
            "        \"nextTime\":167930,\n" +
            "        \"startTime\":160540\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是你成真的美梦，\",\n" +
            "        \"lastTime\":160540,\n" +
            "        \"nextTime\":170970,\n" +
            "        \"startTime\":167930\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"或我青春的始终，\",\n" +
            "        \"lastTime\":167930,\n" +
            "        \"nextTime\":174900,\n" +
            "        \"startTime\":170970\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是我们在对的时间又相逢，\",\n" +
            "        \"lastTime\":170970,\n" +
            "        \"nextTime\":181200,\n" +
            "        \"startTime\":174900\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"故事或许才开始但是结局早已注定，\",\n" +
            "        \"lastTime\":174900,\n" +
            "        \"nextTime\":187280,\n" +
            "        \"startTime\":181200\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是谁先心动也无需分太清，\",\n" +
            "        \"lastTime\":181200,\n" +
            "        \"nextTime\":195300,\n" +
            "        \"startTime\":187280\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"从此每一场电影，\",\n" +
            "        \"lastTime\":187280,\n" +
            "        \"nextTime\":198750,\n" +
            "        \"startTime\":195300\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"每一个特别的心动，\",\n" +
            "        \"lastTime\":195300,\n" +
            "        \"nextTime\":202620,\n" +
            "        \"startTime\":198750\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"都有你见证，\",\n" +
            "        \"lastTime\":198750,\n" +
            "        \"nextTime\":204260,\n" +
            "        \"startTime\":202620\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"而我虔诚的歌颂，\",\n" +
            "        \"lastTime\":202620,\n" +
            "        \"nextTime\":207440,\n" +
            "        \"startTime\":204260\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"致往后余生，\",\n" +
            "        \"lastTime\":204260,\n" +
            "        \"nextTime\":225820,\n" +
            "        \"startTime\":207440\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"当风也暂停，\",\n" +
            "        \"lastTime\":207440,\n" +
            "        \"nextTime\":228480,\n" +
            "        \"startTime\":225820\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"我是你眼里的星，\",\n" +
            "        \"lastTime\":225820,\n" +
            "        \"nextTime\":230750,\n" +
            "        \"startTime\":228480\n" +
            "    },\n" +
            "    {\n" +
            "        \"desc\":\"是长夜将明，\",\n" +
            "        \"lastTime\":228480,\n" +
            "        \"nextTime\":0,\n" +
            "        \"startTime\":230750\n" +
            "    }\n" +
            "]";

}
